public enum GameInputType
{
    Entry,
    Escape,
    FinishedLoading,
    StartPlay,
    PlayerDeath,
    PlayerRespawn,
    OpenPassivesMenu,
    OpenInfoMenu,
    OpenPlayerMenu,
    OpenNewPlayerMenu,
    OpenWorldMenu,
    OpenNewWorldMenu,
    WorldLoaded,
    WorldUnloaded,
    SaveAndExit,
    OpenControlsMenu
}